import { Commander } from './Commander.js';
import { getWip, clearWip, saveWip } from '../utils/wip.js';
import { getValidToken } from '../utils/api.js';
import { apiRequest } from '../utils/api.js';
import { git } from '../utils/git.js';

export class ConfirmCommand extends Commander {
  async execute(args) {
    const wip = getWip();

    // Handle pending PR (from /gtw pr)
    if (wip.pendingPr) {
      const { headBranch, baseBranch, title, body, issueId, workdir } = wip.pendingPr;

      // Ensure branch is pushed to origin
      let wasPushed = false;
      try {
        // Check if branch exists on remote
        git(`git fetch origin ${headBranch}`, workdir);
        const localRev = git(`git rev-parse ${headBranch}`, workdir);
        const remoteRev = git(`git rev-parse origin/${headBranch}`, workdir);
        if (localRev !== remoteRev) {
          git(`git push -u origin ${headBranch}`, workdir);
          wasPushed = true;
        }
      } catch (e) {
        // Branch might not exist on remote yet — push it
        try {
          git(`git push -u origin ${headBranch}`, workdir);
          wasPushed = true;
        } catch (pushErr) {
          return {
            ok: false,
            message: `Failed to push branch ${headBranch}: ${pushErr.message}`,
            display: [
              `❌ Failed to push branch`,
              ``,
              `Branch: ${headBranch}`,
              `Error: ${pushErr.message}`,
              ``,
              `Please push the branch manually and try again.`,
            ].join('\n'),
          };
        }
      }

      // Create PR via GitHub API
      let prData;
      try {
        const token = await getValidToken();
        const repo = wip.repo;

        // Build PR body with issue link if applicable
        let prBody = body || '';
        if (issueId) {
          prBody = `${prBody}\n\n---\nCloses #${issueId}\n_Generated by gtw_`.trim();
        } else {
          prBody = `${prBody}\n\n---\n_Generated by gtw_`.trim();
        }

        prData = await apiRequest('POST', `/repos/${repo}/pulls`, token, {
          title,
          body: prBody,
          head: headBranch,
          base: baseBranch,
        });
      } catch (e) {
        // Preserve wip.pendingPr for retry on GitHub API failure
        return {
          ok: false,
          branch: headBranch,
          message: `GitHub API error: ${e.message}`,
          display: [
            `❌ GitHub API error — PR not created`,
            ``,
            `Error: ${e.message}`,
            ``,
            `Your pending PR draft is preserved. Fix the issue and run /gtw confirm again.`,
          ].join('\n'),
        };
      }

      // PR created successfully — save to wip.pr, clear wip.pendingPr
      const updated = {
        ...wip,
        pr: {
          id: prData.id,
          number: prData.number,
          url: prData.html_url,
          title: prData.title,
          body: prData.body,
          headBranch,
          baseBranch,
          issueId,
          createdAt: new Date().toISOString(),
        },
        pendingPr: undefined,
        updatedAt: new Date().toISOString(),
      };
      saveWip(updated);

      return {
        ok: true,
        pr: updated.pr,
        display: [
          `✅ PR #${prData.number} created`,
          ``,
          `Title: ${prData.title}`,
          `URL: ${prData.html_url}`,
          `Branch: ${headBranch} → ${baseBranch}`,
          issueId ? `Issue: #${issueId}` : '',
        ].filter(Boolean).join('\n'),
      };
    }

    // Handle pending commit (from /gtw push)
    if (wip.pendingCommit) {
      const { title, body, branch, workdir, files, totalAdd, totalDel } = wip.pendingCommit;

      git(`git commit -m "${title.replace(/"/g, '\\"')}" -m "${body.replace(/"/g, '\\"')}"`, workdir);
      git(`git push -u origin ${branch}`, workdir);

      // Keep workdir/repo, clear pendingCommit
      const { workdir: wd, repo } = wip;
      clearWip();
      saveWip({ workdir: wd, repo, updatedAt: new Date().toISOString() });

      return {
        ok: true,
        branch,
        commit: { title, body },
        display: [
          `📦 Committed and pushed`,
          `Branch: ${branch}`,
          `Commit: ${title}`,
          `Extended: ${body.split('\n')[0] || body.slice(0, 60)}`,
        ].join('\n'),
      };
    }

    // Handle pending issue (from /gtw new)
    if (!wip.repo) throw new Error('No pending action. Run /gtw on + /gtw new first');
    if (!wip.issue?.title) throw new Error('No issue draft. Run /gtw new first');

    const token = await getValidToken();
    const { title, body } = wip.issue;

    const data = await apiRequest('POST', `/repos/${wip.repo}/issues`, token, {
      title,
      body: body || 'Created via gtw',
    });

    clearWip();

    return {
      ok: true,
      issue: { id: data.number, url: data.html_url },
      display: `✅ Issue #${data.number} created\n${data.html_url}`,
    };
  }
}
