import { Commander } from './Commander.js';
import { getWip, saveWip } from '../utils/wip.js';
import { git } from '../utils/git.js';
import { getValidToken, apiRequest } from '../utils/api.js';

export class PrCommand extends Commander {
  async execute(args) {
    const wip = getWip();
    if (!wip.workdir) throw new Error('No workdir set. Run /gtw on <workdir> first');
    if (!wip.branch?.name) throw new Error('No branch. Run /gtw fix [name] first');

    const workdir = wip.workdir;
    const branchName = wip.branch.name;

    git(`git push -u origin ${branchName}`, workdir);

    let prBody = '';
    if (wip.issue?.id) {
      try {
        const token = await getValidToken();
        const issue = await apiRequest('GET', `/repos/${wip.repo}/issues/${wip.issue.id}`, token);
        prBody = `## Linked Issue\\nCloses #${wip.issue.id}\\n\\n${issue.body || ''}\\n\\n---\\n_Generated by gtw_`;
      } catch (e) {}
    }

    const updated = {
      ...wip,
      pr: {
        title: wip.pr?.title || `Fix #${wip.issue?.id || ''}: ${branchName}`,
        body: prBody,
      },
      updatedAt: new Date().toISOString(),
    };
    saveWip(updated);

    return {
      ok: true,
      branch: branchName,
      message: `Branch pushed. Run /gtw confirm to create PR`,
      display: `⬆️ Branch pushed to origin\n\nBranch: ${branchName}\n\nRun /gtw confirm to create PR`,
    };
  }
}
